/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_com_yangfan1224_awesome_jni_HelloWorldJNI */

#ifndef _Included_github_com_yangfan1224_awesome_jni_HelloWorldJNI
#define _Included_github_com_yangfan1224_awesome_jni_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     github_com_yangfan1224_awesome_jni_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_github_com_yangfan1224_awesome_jni_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     github_com_yangfan1224_awesome_jni_HelloWorldJNI
 * Method:    sumInteger
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_github_com_yangfan1224_awesome_jni_HelloWorldJNI_sumInteger
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     github_com_yangfan1224_awesome_jni_HelloWorldJNI
 * Method:    sayHelloMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_github_com_yangfan1224_awesome_jni_HelloWorldJNI_sayHelloMe
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     github_com_yangfan1224_awesome_jni_HelloWorldJNI
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lgithub/com/yangfan1224/awesome/jni/UserData;
 */
JNIEXPORT jobject JNICALL Java_github_com_yangfan1224_awesome_jni_HelloWorldJNI_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     github_com_yangfan1224_awesome_jni_HelloWorldJNI
 * Method:    printUserData
 * Signature: (Lgithub/com/yangfan1224/awesome/jni/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_github_com_yangfan1224_awesome_jni_HelloWorldJNI_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
